### ISSUE TITLE
Won't install any mods

### ISSUE THREAD

**Issue by Tropxe** [ShadowChild/BaldursGate3#8]
[debug.log](https://github.com/ShadowChild/BaldursGate3/files/5468580/debug.log)
Once I've selected either of the two BG3 exes (the standard or the DX11 one), I can add mods to the list but the buttons "Install selected mod" and "Toggle enabled" do nothing. In addition, clicking on Settings in Candor does nothing. If I remove a mod from the list and try to add it again, I get an error message saying "<filename> could not be loaded. Please try again." Closing and reopening fixes that. Mods I've tried to use are Tiefling Racials and Devilish Pack, both of which are on the BG3 Nexus. My PC is running Windows 10. The folders seem to be set up correctly since "Open <foldername>" options in Candor do indeed open the corrent folder.

**Comment by zpiddock** [comment]
I have published a hotfix on the Nexus to fix this, If in future an issue like this arises, it also now won't silently error, but instead show a pop up about what went wrong. Hope this helps!
